#!/usr/bin/env bash
# release 
echo $1
echo $2

APP_NAME=$APP_NAME
TAG=$BUILD_TAG
DOCKER_REGISTRY=$DOCKER_REGISTRY
PUSH_TAG=$DOCKER_REGISTRY/apps/$APP_NAME:$TAG


echo "buildkit-docker"
echo "releasing!"
echo 
echo push tag set to $PUSH_TAG

docker tag $APP_NAME:$TAG $PUSH_TAG
echo "TAGGED!"
docker push $PUSH_TAG
